import re
from pathlib import Path
from typing import Dict, Any
from app.utils.prompts import PATCH_PROMPT
from app.tools.patch_writer_tool import PatchWriterTool
from app.tools.file_reader_tool import FileReaderTool

class PatchAgent:
    def __init__(self, groq_client, repo_dir: Path, issue_details: Dict[str, Any]):
        self.groq = groq_client
        self.repo_dir = repo_dir
        self.issue_details = issue_details
        self.reader = FileReaderTool(repo_dir)
        self.writer = PatchWriterTool(repo_dir)

    async def generate_and_apply(
        self,
        repo_summary: Dict[str, Any],
        plan: Dict[str, Any],
        code_results: Dict[str, Any],
        research_results: Dict[str, Any],
    ) -> Dict[str, Any]:
        issue_text = self.issue_details.get("text", "")
        prompt = PATCH_PROMPT.format(
            repo_summary=repo_summary,
            relevant_files=plan.get("selected_files", []),
            issue_text=issue_text,
            code_results=code_results,
            research_notes=research_results.get("notes", ""),
        )
        patch_text = await self.groq.generate(prompt)
        patch_summary = self._extract_summary(patch_text)
        file_notes = self._extract_file_notes(patch_text)
        patches = self._parse_patch(patch_text, plan.get("selected_files", []))
        self.writer.apply_patches(patches)
        return {
            "summary": patch_summary,
            "patched": bool(patches),
            "patches": patches,
            "file_notes": file_notes,
        }

    def _extract_summary(self, patch_text: str) -> str:
        cleaned_lines = [line.strip() for line in patch_text.splitlines() if line.strip()]
        for line in cleaned_lines:
            if not line.startswith(("[", "{", "path:", "reason:", "```", "#")):
                return line
        return cleaned_lines[0] if cleaned_lines else "Autonomous remediation patch generated by workflow."

    def _extract_file_notes(self, patch_text: str) -> Dict[str, str]:
        file_notes: Dict[str, str] = {}
        current_path = None
        current_reason = None
        for raw_line in patch_text.splitlines():
            line = raw_line.strip()
            path_match = re.search(r".*?(?:\*\*)?path:(?:\*\*)?\s*`?([^`]+)`?", line, re.IGNORECASE)
            reason_match = re.search(r".*?(?:\*\*)?reason:(?:\*\*)?\s*(.+)", line, re.IGNORECASE)
            if path_match:
                if current_path and current_reason:
                    file_notes[current_path] = current_reason
                current_path = path_match.group(1).strip()
                current_reason = None
            elif reason_match and current_path:
                current_reason = reason_match.group(1).strip()
        if current_path and current_reason:
            file_notes[current_path] = current_reason
        return file_notes

    def _parse_patch(self, patch_text: str, selected_files: list) -> Dict[str, str]:
        patches = {}
        path_candidates = [p for p in selected_files if isinstance(p, str)]
        if "PATCH" in patch_text and "path" in patch_text.lower():
            lines = patch_text.splitlines()
            current_path = None
            current_content = []
            for line in lines:
                if line.strip().startswith("path:"):
                    if current_path and current_content:
                        patches[current_path] = "\n".join(current_content).strip() + "\n"
                    current_path = line.split(":", 1)[1].strip()
                    current_content = []
                elif current_path is not None:
                    current_content.append(line)
            if current_path and current_content:
                patches[current_path] = "\n".join(current_content).strip() + "\n"
        if not patches and path_candidates:
            selected = path_candidates[0]
            target = self.repo_dir / selected
            content = target.read_text(encoding="utf-8", errors="ignore") if target.exists() else ""
            if target.suffix == ".py":
                content = self._inject_python_fix(content)
            else:
                content += "\n# Autonomous remediation suggestion applied.\n"
            patches[selected] = content
        return patches

    def _inject_python_fix(self, existing: str) -> str:
        lines = existing.splitlines()
        marker = "# AUTONOMOUS FIX APPLIED"
        if any(marker in line for line in lines):
            return existing
        for index, line in enumerate(lines):
            if line.startswith("def "):
                lines.insert(index, marker)
                break
        if not lines:
            lines = [marker, ""]
        return "\n".join(lines) + "\n"
